### ISSUE TITLE
App not working on Meteor 1.4.2.3 (latest)

### ISSUE THREAD

**Issue by arggh** [ManuelDeLeon/phonebook#5]
```sh
While loading npm-bcrypt@0.7.8_2...:
   error: Command failed:
   /Users/arggh/.meteor/packages/meteor-tool/.1.4.2_3.1kyj8us++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
   rebuild --update-binary
   ../src/bcrypt_node.cc:54:18: error: no member named 'Dispose' in
   'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
   callback.Dispose();
   ~~~~~~~~ ^
   ../src/bcrypt_node.cc:128:19: error: unknown type name 'uv_work_t'
   void GenSaltAsync(uv_work_t* req) {
   ^
   ../src/bcrypt_node.cc:137:24: error: unknown type name 'uv_work_t'
   void GenSaltAsyncAfter(uv_work_t* req) {
```
